export const {
  PORT,
  ALLOWED_ORIGIN,
  MONGODB_URI,
  SENTRY_DSN,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASS,
  FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_PRIVATE_KEY
} = process.env;
